site_name: Ihsan Salari - Project Docs
site_url: https://www.docs.ihsan.cc
theme:
  name: material
  font: 
    text: Courier Prime
  features:
    - navigation.instant
    - navigation.tabs
    # - navigation.sections
    - toc.integrate
    # - navigation.top
    # - search.suggest
    # - search.highlight
    # - content.tabs.link
    # - content.code.annotation
    # - content.code.copy
    # - navigaation.expand
    - navigation.indexes
    - navigation.tabs.sticky
    - navigation.tracking
    - header.autohide

  language: en
  palette:
    - scheme: custom-dark
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: custom-light
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode 


nav: 
  - Home: index.md
  - Projects: 
    - Projects Home: Projects/index.md
    - Business Card:
      - Revision 1: 
        - Projects/BusinessCard/Rev1/index.md
        - Hardware design: Projects/BusinessCard/Rev1/hardwareDesign.md
        - Firmware design: Projects/BusinessCard/Rev1/firmware.md
    - DC to DC: Projects/DC_DC/index.md
    - Ionic (EHD) Thruster:
      - Projects/IonicThruster/index.md
    - LED Flood Light Panels:
      - Projects/LEDLightPanels/index.md
      - 20V Panel:
        - Projects/LEDLightPanels/20V_Panel/index.md
    - Lorentz Solver:
      - Projects/LorentzSolver/index.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://www.github.com/ihsan-sa
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ihsan-sa
    - icon: fontawesome/solid/envelope
      link: mailto:hi@ihsan.cc
  
  generator: false


copyright: © 2025 Ihsan Salari

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js



extra_css:
  - css/extra.css