site_name: Ihsan Salari - Project Docs
site_url: https://www.docs.ihsan.cc
theme:
  name: material
  font: 
    text: Courier Prime
  toc:
    toc_depth: 2
  features:
    - navigation.instant
    - navigation.tabs
    # - navigation.sections
    - toc.integrate
    # - navigation.top
    # - search.suggest
    # - search.highlight
    # - content.tabs.link
    # - content.code.annotation
    # - content.code.copy
    # - navigaation.expand
    - navigation.indexes
    - navigation.tabs.sticky
    - navigation.tracking
    - header.autohide
    - content.code.copy

  language: en
  palette:
    - scheme: custom-dark
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: custom-light
      toggle:
        icon: material/weather-night
        name: Switch to dark mode 


nav: 
  - Home: 
    - Overview: index.md
  - Projects: 
    - Projects Home: Projects/index.md
    - Business Card:
      - Revision 1: 
        - Overview: Projects/BusinessCard/Rev1/overview.md
        - Hardware design: Projects/BusinessCard/Rev1/hardwareDesign.md
        - Firmware design: Projects/BusinessCard/Rev1/firmware.md
    - DC to DC: 
      - Overview: Projects/DC_DC/overview.md
    - Ionic (EHD) Thruster:
      - Overview: Projects/IonicThruster/overview.md
    - LED Flood Light Panels:
      - Overview: Projects/LEDLightPanels/overview.md
      - 20V Panel:
        - Overview: Projects/LEDLightPanels/20V_Panel/overview.md
    - Lorentz Solver:
      - Overview: Projects/LorentzSolver/overview.md
      - Installation and Setup: Projects/LorentzSolver/setup.md
      - Simulation Configuration: Projects/LorentzSolver/config.md
      - Physics and Math: Projects/LorentzSolver/physics.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://www.github.com/ihsan-sa
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ihsan-sa
    - icon: fontawesome/solid/envelope
      link: mailto:hi@ihsan.cc
    - icon: fontawesome/solid/globe
      link: https://www.ihsan.cc
      name: ihsan.cc
  
  generator: false


copyright: © 2025 Ihsan Salari &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="https://www.ihsan.cc">www.ihsan.cc</a>

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 6
  - pymdownx.arithmatex:
      generic: true
  - admonition:
  - pymdownx.superfences:
  - pymdownx.highlight:
      linenums: true


extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js



extra_css:
  - css/extra.css